import type { StoryEvent } from './types';

export const STORY_EVENTS: StoryEvent[] = [
  {
    id: 'intro-family-world-stage',
    delivery: 'scene',
    once: true,
    priority: 100,
    trigger: { type: 'first_launch' },
    lines: [
      { speaker: '아빠', portraitKey: 'char_dad', text: '정우야, 이번엔 물고기 말고 과녁이구나.' },
      { speaker: '엄마', portraitKey: 'char_mom', text: '점수도 중요하지만, 먼저 숨부터 맞추자.' },
      { speaker: '세연', portraitKey: 'char_seyeon', text: '오빠, 정중앙 맞히면 내가 제일 먼저 안아줄게!' },
      { speaker: '정우', portraitKey: 'char_jeongwoo', text: '좋아. 우리 가족 이름으로 정중앙을 노려볼게.' },
    ],
  },
  {
    id: 'first-calibration-complete',
    delivery: 'overlay',
    once: true,
    priority: 90,
    trigger: { type: 'first_calibration_complete' },
    lines: [
      { speaker: '엄마', portraitKey: 'char_mom', text: '오, 자세가 잡히니까 눈빛도 달라졌네.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '좋다. 이제 힘보다 반복이다.' },
    ],
  },
  {
    id: 'first-ten-toast',
    delivery: 'toast',
    once: true,
    priority: 80,
    trigger: { type: 'first_ten' },
    lines: [{ speaker: '세연', portraitKey: 'char_seyeon', text: '와, 딱 10점이야! 지금 느낌 좋다!' }],
  },
  {
    id: 'first-bullseye-toast',
    delivery: 'toast',
    once: true,
    priority: 85,
    trigger: { type: 'first_bullseye' },
    lines: [{ speaker: '세연', portraitKey: 'char_seyeon', text: '한가운데다! 명예의 전당 맨 위도 노려보자!' }],
  },
  {
    id: 'low-score-encourage',
    delivery: 'overlay',
    cooldownMatches: 1,
    priority: 70,
    trigger: { type: 'low_score_streak' },
    lines: [
      { speaker: '엄마', portraitKey: 'char_mom', text: '괜찮아. 급하게 당기지 말고 숨부터 맞추자.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '한 발씩 끊어가면 흐름은 다시 온다.' },
    ],
  },
  {
    id: 'personal-best-overlay',
    delivery: 'overlay',
    cooldownMatches: 1,
    priority: 88,
    trigger: { type: 'personal_best' },
    lines: [
      { speaker: '아빠', portraitKey: 'char_dad', text: '오늘의 넌 어제의 널 이겼다.' },
      { speaker: '세연', portraitKey: 'char_seyeon', text: '명예의 전당 맨 위로 슬금슬금 올라간다!' },
    ],
  },
  {
    id: 'ranking-mode-unlocked',
    delivery: 'scene',
    once: true,
    priority: 95,
    trigger: { type: 'mode_unlocked', unlockedMode: 'ranking72' },
    lines: [
      { speaker: '엄마', portraitKey: 'char_mom', text: '이제 진짜 긴 호흡의 무대가 열렸네.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '여기서부터는 실력도 중요하지만 마음도 중요하다.' },
      { speaker: '정우', portraitKey: 'char_jeongwoo', text: '좋아. 다음엔 끝까지 차분하게 버텨볼게.' },
    ],
  },
  {
    id: 'ending-gold',
    delivery: 'scene',
    cooldownMatches: 1,
    priority: 92,
    trigger: { type: 'match_end', resultBand: 'gold' },
    lines: [
      { speaker: '세연', portraitKey: 'char_seyeon', text: '우와, 오늘은 거의 금빛 모드였어!' },
      { speaker: '엄마', portraitKey: 'char_mom', text: '집중도 좋았고 흔들릴 때도 다시 돌아왔어.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '이 정도면 다음 무대에서도 당당하겠다.' },
    ],
  },
  {
    id: 'ending-silver',
    delivery: 'scene',
    cooldownMatches: 1,
    priority: 91,
    trigger: { type: 'match_end', resultBand: 'silver' },
    lines: [
      { speaker: '엄마', portraitKey: 'char_mom', text: '은빛처럼 차분하고 단단한 경기였어.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '조금만 더 다듬으면 더 높은 곳도 충분하다.' },
    ],
  },
  {
    id: 'ending-bronze',
    delivery: 'scene',
    cooldownMatches: 1,
    priority: 90,
    trigger: { type: 'match_end', resultBand: 'bronze' },
    lines: [
      { speaker: '아빠', portraitKey: 'char_dad', text: '오늘도 기록을 하나 더 쌓았다. 그게 제일 중요하다.' },
      { speaker: '세연', portraitKey: 'char_seyeon', text: '반짝반짝 동빛이야! 다음엔 더 위로 가자!' },
    ],
  },
  {
    id: 'ending-encourage',
    delivery: 'scene',
    cooldownMatches: 1,
    priority: 89,
    trigger: { type: 'match_end', resultBand: 'encourage' },
    lines: [
      { speaker: '엄마', portraitKey: 'char_mom', text: '결과보다 더 중요한 건 끝까지 놓지 않았다는 거야.' },
      { speaker: '아빠', portraitKey: 'char_dad', text: '가족 응원은 점수와 상관없이 계속 간다.' },
      { speaker: '정우', portraitKey: 'char_jeongwoo', text: '응. 다음 판엔 더 차분하게 하나씩 맞혀볼게.' },
    ],
  },
  {
    id: 'home-comment-steady',
    delivery: 'toast',
    priority: 10,
    trigger: { type: 'home_comment' },
    lines: [{ speaker: '엄마', portraitKey: 'char_mom', text: '오늘은 자세가 더 차분했네.' }],
  },
  {
    id: 'home-comment-joke',
    delivery: 'toast',
    priority: 10,
    trigger: { type: 'home_comment' },
    lines: [{ speaker: '아빠', portraitKey: 'char_dad', text: '활줄보다 마음줄부터 팽팽하게 가보자.' }],
  },
  {
    id: 'home-comment-hype',
    delivery: 'toast',
    priority: 10,
    trigger: { type: 'home_comment' },
    lines: [{ speaker: '세연', portraitKey: 'char_seyeon', text: '오늘 Top 5 카드에 이름 하나 더 올리는 거야!' }],
  },
];
